version: "3.9"

volumes:
  elasticsearch:
    driver: local
  node_modules:
    driver: local

services:
  redis:
    image: redis
    container_name: kibanalytics.redis
    restart: unless-stopped
    hostname: redis
    volumes:
      - .config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "${REDIS_LISTEN:-127.0.0.1:6379}:6379"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: kibanalytics.logtstash
    depends_on:
      - redis
    restart: unless-stopped
    hostname: logstash
    volumes:
      - .config/logstash/pipeline/:/usr/share/logstash/pipeline/
      - .config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    env_file:
      - .env
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  elasticsearch:
    profiles: [ "development" ]
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: kibanalytics.elasticsearch
    depends_on:
      - logstash
    restart: unless-stopped
    hostname: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - "discovery.seed_hosts=127.0.0.1:9300"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibanalytics.kibana
    restart: unless-stopped
    hostname: kibana
    volumes:
      - .config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    env_file:
      - .env
    ports:
      - "${KIBANA_LISTEN:-5601}:5601"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  node:
    profiles: [ "production" ]
    container_name: kibanalytics.node
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    hostname: node
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - ${EXPRESS_LISTEN:-80}:3000
    working_dir: /app
    command: node ./index.js
    env_file:
      - .env
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}
